// Generated by gencpp from file rcProjPkg/data_msg.msg
// DO NOT EDIT!


#ifndef RCPROJPKG_MESSAGE_DATA_MSG_H
#define RCPROJPKG_MESSAGE_DATA_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcProjPkg
{
template <class ContainerAllocator>
struct data_msg_
{
  typedef data_msg_<ContainerAllocator> Type;

  data_msg_()
    : x(0.0)
    , y(0.0)  {
    }
  data_msg_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::rcProjPkg::data_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcProjPkg::data_msg_<ContainerAllocator> const> ConstPtr;

}; // struct data_msg_

typedef ::rcProjPkg::data_msg_<std::allocator<void> > data_msg;

typedef boost::shared_ptr< ::rcProjPkg::data_msg > data_msgPtr;
typedef boost::shared_ptr< ::rcProjPkg::data_msg const> data_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcProjPkg::data_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcProjPkg::data_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcProjPkg::data_msg_<ContainerAllocator1> & lhs, const ::rcProjPkg::data_msg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcProjPkg::data_msg_<ContainerAllocator1> & lhs, const ::rcProjPkg::data_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcProjPkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rcProjPkg::data_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcProjPkg::data_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcProjPkg::data_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcProjPkg::data_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcProjPkg::data_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcProjPkg::data_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcProjPkg::data_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::rcProjPkg::data_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rcProjPkg::data_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcProjPkg/data_msg";
  }

  static const char* value(const ::rcProjPkg::data_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcProjPkg::data_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::rcProjPkg::data_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcProjPkg::data_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcProjPkg::data_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcProjPkg::data_msg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCPROJPKG_MESSAGE_DATA_MSG_H
